### ISSUE TITLE
Wow! Any possibility of getting the bcrypt module out for 2.12?

### ISSUE THREAD

**Issue by i-am-the-slime** [ldaniels528/means-js#4]
I am impressed! I found this repo by looking for webjars for bcrypt.
My question is in the issue title!

**Comment by ldaniels528** [comment]
When you say 2.12, do you mean Scala 2.12.x?

**Comment by webmonarch** [comment]
👍 regarding getting a build for Scala 2.12.x.  Appologies, I am a new to the Scala/js ecosystem.  Tweaking the `build.sbt` led to dep failures that I couldn't immediately resolve.

I am happy to help with a little direction.  cheers.

**Comment by ldaniels528** [comment]
Welcome to Scala.js!

I've actually been working on the next major release of this project, in which I've also ported it to Scala 2.12 and Scala.js 0.6.14 (see link below). I must warn you, this is a code breaking release as the package hierarchy is completely different (org.scalajs.xxx has been changed to io.scalajs.xxx). Additionally, because of new functionality in Scala.js 0.6.14, I'm removing the "require" function as it will no longer be necessary. Please see the code under ./src/test/scala in each sub project/module for examples. I'll be updating the README.md soon to reflect all of the changes.

Cheers.

https://github.com/ldaniels528/scalajs-node-npm/tree/feature/scala-2.12

**Comment by 2m** [comment]
Looking forward to the new release for Scala 2.12!
